name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1